### ISSUE TITLE
Hi Zhou, i want to know wheather the asymmetric label noise is generated like previous method UNICON?

### ISSUE THREAD

**Issue by LanXiaoPang613** [yuyinzhou/L2B#4]
Hi Zhou, i want to know wheather the asymmetric label noise is generated like previous method unicon?Actually, I saw `flip` and `flip2` in the code, but I did not see the asymmetric label noise generation function used in `unicon`, such as cat<->dog, bird->plane, etc.

**Comment by LanXiaoPang613** [comment]
besides, when i read the code, i found that the loss l_f_meta is zero when multiplied by eps. It indicates that the gradient is 0. So i want to understand the purpose of this operation.
![image](https://github.com/yuyinzhou/L2B/assets/35187545/b0ec2835-2153-4b87-8ac4-ba2e85779377)

**Comment by yuyinzhou** [comment]
Thanks for your interest in our work!

1. We follow previous implementation in dividemix to generate asymmetric noise. 

2. For the initialization of l_f_meta, we follow the approach of Ren et al. in "Learning to Reweight Examples for Robust Deep Learning," where the initialization value is set to zero.
